### ISSUE TITLE
No zoom in chatgpt web-site

### ISSUE THREAD

**Issue by shitpoet** [nizioleque/mouse-pinch-to-zoom#10]
For some reason, this site is not zoomable with the extension.

**Comment by nizioleque** [comment]
Hi, for me it's working correctly on chatgpt.com. I have no idea why it's not working for you. Could you tell me what browser you're using and what are your extension settings? Maybe you have another extension installed that's interfering?

**Comment by shitpoet** [comment]
Yes, you're right. I've tried to disable my other extensions one by one, and the culprit is MyStyle  - a small extension to add some custom CSS styles per site. I use my own fork, and I believe the problematic code is the following:

```
    //var body = document.body;
    const html = document.querySelector('html')

    var style = document.createElement('style');
    var textarea = document.createElement('textarea');

    // hide textarea by default
    textarea.style.display = 'none';
    textarea.id = 'my-style-input';
    textarea.spellcheck = false;

    //head.appendChild(style);
    //body.appendChild(textarea);
    html.appendChild(style);
    html.appendChild(textarea);
```

Here, we add a `textarea` to `html` - theoretically, it can lead to the auto-creation of `body` element. At least this is my hypothesis. I don't remember if it's my edits or not, and why we adding a textarea to `html` instead of `body`.

I toggled the comments and now your extension works on `chatgpt.com` just fine.

**Comment by shitpoet** [comment]
I've patched my problematic MyStyle fork to add `style` element to the `<head>` instead of the `<body>` with waiting until the `<head>` really exists. This resolves the issue.
