### ISSUE TITLE
Firefox version?

### ISSUE THREAD

**Issue by koeliga** [nizioleque/mouse-pinch-to-zoom#2]
Hello, I saw on the chrome extension support page that you were working on the firefox version. Is this still in development? I would really appreciate it if you could update the extension to also work on firefox

**Comment by nizioleque** [comment]
Hi, thank you for the reminder :)

I uploaded it to the Firefox store yesterday and it just got approved! Get it here: https://addons.mozilla.org/en-US/firefox/addon/mouse-pinch-to-zoom/

I also recommend checking out my other popular extension: https://addons.mozilla.org/en-US/firefox/addon/youtube-custom-speed/

If you find any issues please let me know (email or open another issue)
